Firefox support
fzyzcjy/flutter_rust_bridge pull request #1188
Opened 2023-04-21 00:29 UTC by LemonHX

## Changes

Fixes #1187

## Checklist

- [x] An issue to be fixed by this PR is listed above.
- [ ] New tests are added to ensure new features are working. End-to-end tests are usually in the `./frb_example/pure_dart` example, more specifically, `rust/src/api.rs` and `dart/lib/main.dart`.
- [ ] The code generator is run and the code is formatted (via `just precommit`).
- [ ] If this PR adds/changes features, documentations (in the `./book` folder) are updated.
- [ ] CI is passing.

## Remark for PR creator

- Justfile is a task runner for the command line interface that allows you to run shell commands from a file named `justfile` in your project directory. You can use Justfile after [installing it](https://github.com/casey/just). Note that commands written in `justfile` of this repository are expected to be run in `bash`, not `cmd` or `powershell`. Running `just ...` commands in `cmd` or `powershell` will produce errors as the syntax is not compatible. On Windows, you can use `git bash` if you have Git installed.
- If fzyzcjy does not reply for a few days, maybe he just did not see it, so please ping him.

2023-04-21 00:32 UTC, fzyzcjy commented
The feature looks good! cc @Desdaemon who implemented the web part

2023-07-10 09:27 UTC, LemonHX commented
hello?

2023-07-10 10:15 UTC, fzyzcjy commented
@Desdaemon - do you think this PR is OK? If so I will merge it :)

2023-07-10 11:16 UTC, Desdaemon requested changes
Just a nit, looks good so far!

2023-07-23 12:33 UTC, LemonHX commented on frb_dart/bin/serve.dart
> +      defaultsTo: true)
that will be greater

2023-09-21 22:55 UTC, fzyzcjy commented
👀 

(this is mergeable once CI is green)

2023-12-21 01:19 UTC, closed without merging

2023-12-21 01:19 UTC, fzyzcjy commented
IMHO this is supported in v2. Thank you all the same for the PR, and feel free to create an issue if it does not work in v2!